refactor configuration handling

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -38,6 +38,26 @@ QXT_VARS=$QXT_BUILD_TREE/features/qxtvars.prf
 [ -f $QMAKE_CACHE ] && mv $QMAKE_CACHE $QMAKE_CACHE.bak
 [ -f $QXT_VARS ] && mv $QXT_VARS $QXT_VARS.bak
 
+writeCacheAndVars()
+{
+  echo $1 >> $QMAKE_CACHE
+  echo $1 >> $QXT_VARS
+}
+
+writeDefine()
+{
+  writeCacheAndVars "DEFINES += $1"
+}
+
+writeHave()
+{
+  if [ "$2" == "1" ]; then
+    writeDefine "QXT_HAVE_$1"
+  else
+    writeDefine "QXT_NO_$1"
+  fi
+}
+
 # colors
 C_RED='\e[1;31m'
 C_BLUE='\e[1;34m'
@@ -55,16 +75,20 @@ while (( $# > 0 )); do
     if [ $1 == "-qmake-bin" ]; then
         QMAKE_BIN=$2; shift
     elif [ $1 == "-L" ]; then
-        echo "LIBS += -L$2" >> $QMAKE_CACHE;shift
+        echo "LIBS += -L$2" >> $QMAKE_CACHE; shift
     elif [ $1 == "-l" ]; then
-        echo "LIBS += -l$2" >> $QMAKE_CACHE;shift
+        echo "LIBS += -l$2" >> $QMAKE_CACHE; shift
     elif [ $1 == "-I" ]; then
-        echo "INCLUDEPATH += $2" >> $QMAKE_CACHE;shift
+        echo "INCLUDEPATH += $2" >> $QMAKE_CACHE; shift
     elif [ $1 == "-bootstrap" ]; then
-        echo "CONFIG += bootstrap" >> $QMAKE_CACHE; shift
+        echo "CONFIG += bootstrap" >> $QMAKE_CACHE
     elif [ $1 == "-nomake" ]; then
-        echo "QXT_MODULES -= $2" >> $QMAKE_CACHE
-        echo "QXT_MODULES -= $2" >> $QXT_VARS; shift
+        writeCacheAndVars "QXT_MODULES -= $2"; shift
+    elif [ $1 == "-asan" ]; then
+        writeCacheAndVars "QMAKE_CXXFLAGS_DEBUG += -fsanitize=address"
+        writeCacheAndVars "QMAKE_LFLAGS_DEBUG += -lasan"
+    elif [ $1 == "-no-pkgconfig" ]; then
+        echo "CONFIG += no_pkgconfig" >> $QMAKE_CACHE
     elif [ $1 == "-prefix" ]; then
         QXT_INSTALL_PREFIX=$2; shift
     elif [ $1 == "-libdir" ]; then
@@ -95,11 +119,8 @@ while (( $# > 0 )); do
     elif [ $1 == "-no-openssl" ]; then
         NO_OPENSSL=1
         NO_LIBSSH=1
-        echo "DEFINES += QT_NO_OPENSSL NO_LIBSSH" >> $QMAKE_CACHE
-        echo "DEFINES -= HAVE_OPENSSL" >> $QMAKE_CACHE
     elif [ $1 == "-no-libssh" ]; then
         NO_LIBSSH=1
-        echo "DEFINES += NO_LIBSSH" >> $QMAKE_CACHE
     elif [ $1 == "-no-avahi" ]; then
         echo "CONFIG += NO_AVAHI" >> $QMAKE_CACHE
     elif [ $1 == "-verbose" ]; then
@@ -119,7 +140,7 @@ while (( $# > 0 )); do
         echo "Usage: configure [-prefix <dir>] [-libdir <dir>] [-docdir <dir>]"
         echo "       [-bindir <dir>] [-headerdir <dir>] [-featuredir <dir> ]"
         echo "       [-qmake-bin <path>] [-static] [-debug] [-release]"
-        echo "       [-no-db] [-no-zeroconf] [-nomake <module>]"
+        echo "       [-no-db] [-no-zeroconf] [-nomake <module>] [-asan]"
         if [[ "$QXT_MAC" == "0" ]]; then
             echo -n "       [-no-xrandr] [-qws]"
         else
@@ -160,6 +181,8 @@ while (( $# > 0 )); do
         echo "-no-avahi ........... Apple mdns-sd instead of avahi even on linux"
         echo "-nomake <module> .... Do not compile the specified module"
         echo "                      options: $QXT_MODULES"
+        echo "-asan                 If in debug mode, build using Address Sanitizer"
+        echo "-no-pkgconfig         Do not generate .pc or .prl files"
         echo "-verbose ............ Show full compiler output"
         echo "-coverage ........... Collect coverage information"
         if [[ "$QXT_MAC" == "1" ]]; then
@@ -216,18 +239,12 @@ if [[ "$QXT_INSTALL_FEATURES" == "" ]]; then
 fi
 
 # output variables
-echo "QXT_INSTALL_PREFIX = $QXT_INSTALL_PREFIX" >> $QMAKE_CACHE
-echo "QXT_INSTALL_PREFIX = $QXT_INSTALL_PREFIX" >> $QXT_VARS
-echo "QXT_INSTALL_LIBS = $QXT_INSTALL_LIBS" >> $QMAKE_CACHE
-echo "QXT_INSTALL_LIBS = $QXT_INSTALL_LIBS" >> $QXT_VARS
-echo "QXT_INSTALL_BINS = $QXT_INSTALL_BINS" >> $QMAKE_CACHE
-echo "QXT_INSTALL_BINS = $QXT_INSTALL_BINS" >> $QXT_VARS
-echo "QXT_INSTALL_HEADERS = $QXT_INSTALL_HEADERS" >> $QMAKE_CACHE
-echo "QXT_INSTALL_HEADERS = $QXT_INSTALL_HEADERS" >> $QXT_VARS
-echo "QXT_INSTALL_FEATURES = $QXT_INSTALL_FEATURES" >> $QMAKE_CACHE
-echo "QXT_INSTALL_FEATURES = $QXT_INSTALL_FEATURES" >> $QXT_VARS
-echo "QXT_INSTALL_DOCS = $QXT_INSTALL_DOCS" >> $QMAKE_CACHE
-echo "QXT_INSTALL_DOCS = $QXT_INSTALL_DOCS" >> $QXT_VARS
+writeCacheAndVars "QXT_INSTALL_PREFIX = $QXT_INSTALL_PREFIX"
+writeCacheAndVars "QXT_INSTALL_LIBS = $QXT_INSTALL_LIBS"
+writeCacheAndVars "QXT_INSTALL_BINS = $QXT_INSTALL_BINS"
+writeCacheAndVars "QXT_INSTALL_HEADERS = $QXT_INSTALL_HEADERS"
+writeCacheAndVars "QXT_INSTALL_FEATURES = $QXT_INSTALL_FEATURES"
+writeCacheAndVars "QXT_INSTALL_DOCS = $QXT_INSTALL_DOCS"
 echo "QXT_SOURCE_TREE = $QXT_SOURCE_TREE" >> $QMAKE_CACHE
 echo "QXT_BUILD_TREE = $QXT_BUILD_TREE" >> $QMAKE_CACHE
 
@@ -251,46 +268,41 @@ fi
 # detect dependencies
 configtest()
 {
-    echo -en "Checking for $1 "
-    echo -e  " \n\n $1\n" >>$CONFIG_LOG
-    mkdir -p "$QXT_BUILD_TREE/config.tests/$1"
-    cd "$QXT_BUILD_TREE/config.tests/$1"
-    $QMAKE_BIN $QMAKE_PARAMS "$QXT_SOURCE_TREE/config.tests/$1/$1.pro" >>$CONFIG_LOG
-    echo -n "."
-    $MAKE clean >>$CONFIG_LOG 2>&1
-    [ -f ./$1 ] && rm ./$1
-    echo -n "."
-    $MAKE >>$CONFIG_LOG 2>&1 >>$CONFIG_LOG 2>&1
-    if [ -x $1 ] ; then
-        echo -e >&2 "  [${C_GREEN}success${C_NONE}] "
-        echo "DEFINES+=HAVE_$2">>$QMAKE_CACHE
+    if [ "$3" == "1" ]; then
+        writeHave $2 0
     else
-        echo -e >&2 "  [${C_RED}failure${C_NONE}] "
+        echo -en "Checking for $1 "
+        echo -e  " \n\n $1\n" >>$CONFIG_LOG
+        mkdir -p "$QXT_BUILD_TREE/config.tests/$1"
+        cd "$QXT_BUILD_TREE/config.tests/$1"
+        $QMAKE_BIN $QMAKE_PARAMS "$QXT_SOURCE_TREE/config.tests/$1/$1.pro" >>$CONFIG_LOG
+        echo -n "."
+        $MAKE clean >>$CONFIG_LOG 2>&1
+        [ -f ./$1 ] && rm ./$1
+        echo -n "."
+        $MAKE >>$CONFIG_LOG 2>&1 >>$CONFIG_LOG 2>&1
+        if [ -x $1 ] ; then
+            echo -e >&2 "  [${C_GREEN}success${C_NONE}] "
+            writeHave $2 1
+        else
+            echo -e >&2 "  [${C_RED}failure${C_NONE}] "
+            writeHave $2 0
+        fi
     fi
 }
 
 echo >&2 "Testing for optional external libraries."
 echo >&2 "If tests fail, some features will not be available."
 
-configtest qt4 QT
-if [[ "$NO_DB" == "0" ]]; then
-    configtest db DB
-fi
-
-if [[ "$NO_OPENSSL" == "0" ]]; then
-    configtest openssl OPENSSL
-fi
+configtest qt4 QT 0
+configtest db DB $NO_DB
+configtest openssl OPENSSL $NO_OPENSSL
+configtest xrandr XRANDR $NO_XRANDR
 
 if [[ "$QXT_MAC" == "0" ]]; then
-    if [[ "$NO_XRANDR" == "0" ]]; then
-        configtest xrandr XRANDR
-    fi
-
-    if [[ "$NO_ZEROCONF" == "0" ]]; then
-        configtest zeroconf ZEROCONF
-    fi
+    configtest zeroconf ZEROCONF $NO_ZEROCONF
 else
-    echo "DEFINES+=HAVE_ZEROCONF">>$QMAKE_CACHE
+    writeHave ZEROCONF 1
 fi
 
 # run qmake
